export const LOAD_SUBSCRIBERS = 'bdt/App/LOAD_SUBSCRIBERS';
export const LOAD_SUBSCRIBERS_SUCCESS = 'bdt/App/LOAD_SUBSCRIBERS_SUCCESS';
export const LOAD_SUBSCRIBERS_ERROR = 'bdt/App/LOAD_SUBSCRIBERS_ERROR';
export const REMOVE_SUBSCRIBER = 'bdt/App/REMOVE_SUBSCRIBER';
export const REMOVE_SUBSCRIBER_SUCCESS = 'bdt/App/REMOVE_SUBSCRIBER_SUCCESS';
export const REMOVE_SUBSCRIBER_ERROR = 'bdt/App/REMOVE_SUBSCRIBER_ERROR';
